tenant: "public"
namespace: "default"
name: "red-function"
className: "org.apache.pulsar.functions.api.examples.RedFunction"
inputs: ["input_topic"]
output: "output_topic"
autoAck: true
parallelism: 1